Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/do_site", line 8, in <module>
    sys.exit(go())
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/cloudgenix_config/do.py", line 9279, in go
    with open(config_file, 'r') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: 'Branch 2.yml'
